[package]
name = "file_organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.8.2"
chrono = "0.4.42"
clap = { version = "4.5", features = ["derive"] }
notify = "8.2.0"
num_cpus = "1.17"
